days = 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25

all: $(patsubst %,   Day%, $(days))
Day%: 
	mkdir $@
	echo . > ./$@/input.txt
	echo # $@ Part 1 > ./$@/pt1.py
	echo # $@ Part 2 > ./$@/pt2.py
